using System;

namespace MiniPL.tokens {

  public enum MiniPLTokenType {
      
    INVALID_TOKEN,
    PLUS,
    MINUS,
    ASTERISK,
    SLASH,
    LOGICAL_AND,
    LOGICAL_NOT,
    EQUALITY_COMPARISON,
    LESS_THAN_COMPARISON,
    SEMICOLON,
    LEFT_PARENTHESIS,
    RIGHT_PARENTHESIS,
    QUOTE,
    BACKSLASH,
    ASSIGNMENT_OPERATOR,
    RANGE_OPERATOR,
    ONE_LINE_COMMENT_DELIMITER,
    MULTI_LINE_COMMENT_LEFT_DELIMITER,
    MULTI_LINE_COMMENT_RIGHT_DELIMITER,
    TYPE_IDENTIFIER_INTEGER,
    TYPE_IDENTIFIER_STRING,
    TYPE_IDENTIFIER_BOOL,
    KEYWORD_VAR,
    KEYWORD_FOR,
    KEYWORD_END,
    KEYWORD_IN,
    KEYWORD_DO,
    KEYWORD_READ,
    KEYWORD_PRINT,
    KEYWORD_ASSERT,
    IDENTIFIER,
    STRING_LITERAL,
    INTEGER_LITERAL

  }
}